# Generated by Django 2.2.19 on 2022-08-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('obrigatoria', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('ementa', models.TextField(blank=True, max_length=500, verbose_name='Ementa')),
                ('bibliografia', models.TextField(blank=True, max_length=500, verbose_name='Bibliografia')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
    ]
