# Generated by Django 2.2.19 on 2022-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_auto_20220813_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='professor',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='professor',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='professor',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
    ]
