# Generated by Django 2.2.19 on 2022-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_auto_20220827_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='curriculo',
            field=models.TextField(blank=True, null=True, verbose_name='Currículo'),
        ),
    ]
