# Generated by Django 2.2.19 on 2022-08-27 20:39

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_professor_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Imagem'),
        ),
    ]
